### ISSUE TITLE
Error with container with capabilities dropped

### ISSUE THREAD

**Issue by ehsanmostajeran** [zuBux/drydock#6]
Hi, I get error if any one my containers has capabilities dropped.  

Traceback (most recent call last):
  File "drydock.py", line 99, in <module>
    main()
  File "drydock.py", line 86, in main
    audit.run_audits(auditcat)
  File "/drydock/audits/audit.py", line 43, in run_audits
    res = self.call(audit)
  File "/drydock/audits/audit.py", line 22, in call
    return getattr(self, audit)()
  File "/drydock/audits/containers.py", line 151, in kernel_capabilities
    %len(container_caps)
TypeError: not all arguments converted during string formatting

**Comment by zuBux** [comment]
Hi! Thanks for reporting the issue!

I 'll have a look later this afternoon.
